version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin@12345"
      MSSQL_DATABASE: "UserApp"
      
    ports:
      - "1433:1433"
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    
    ports:
      - 5672:5672
      - 15672:15672